
services:
  csv_converter:
    build:
      context: .
      dockerfile: ./ops/Dockerfile
    volumes:
      - ./app/data:/app/data
    deploy:
      resources:
        limits:
          cpus: '8.0'

